name: Cypress CI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install

      - name: Create cypress.env.json file
        run: |
          echo "{
            \"USERNAME\": \"$USERNAME\",
            \"PASSWORD\": \"$PASSWORD\"
          }" > cypress.env.json
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots
