name: Cypress CI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install

      - name: Create cypress.env.json file
        run: |
          touch cypress.env.json
          echo USERNAME=${{secrets.USERNAME}} >> cypress.env.json
          echo PASSWORD=${{secrets.PASSWORD}} >> cypress.env.json
          cat cypress.env.json

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots
