name: Cypress CI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci

      - name: Create cypress.env.json file
        run: |
          echo "{
            \"USERNAME\": \"$USERNAME\",
            \"PASSWORD\": \"$PASSWORD\"
          }" > cypress.env.json
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports
