name: On Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  lint:
  name: Static code analysis
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: npm install

    - name: Static code analysis
      run: npm run lint
